version: "3.9"
services:
  web:
    build: .
    ports:
      - "8000:5000"

  db:
    image: postgres:14.4-alpine
    restart: always
    ports:
      - "5050:5050"
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - ./config/local.env

volumes:
  db:
